# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    # Check Public IP address
    - name: Check Public IP address
      run: curl myip.ipip.net 

    # Retrieve oc CLI
    - name: Retrieve oc CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.3.18.tar.gz
        tar zxvf openshift-client-linux-4.3.18.tar.gz -C /usr/local/bin
        oc version

    # Runs a set of commands using the runners shell
    - name: Run a Docker
      run: |
        docker run -d -p 5000:5000 --name mirror-registry registry:2
        curl -v 127.0.0.1:5000/v2/_catalog
